# Generated by Django 3.0.3 on 2020-05-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20200511_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
